[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lapp = "0.4.0"
lazy_static = "1.4.0"
libarena = "0.1.6"
regex = "1"
typed-arena = "2.0.2"
